### ISSUE TITLE
Cleaner ONE=MOR image

### ISSUE THREAD

**Issue by tabacitu** [the-whole-fruit/manifesto#5]
![IMAGE 2020-10-22 12:48:00](https://user-images.githubusercontent.com/1032474/96904274-e3703980-1464-11eb-9749-b388ca75d061.jpg)

**Comment by iordacheandrei** [comment]
![ONEisMOR](https://user-images.githubusercontent.com/71145983/96904409-c016b000-149f-11eb-95e8-a33c63222ca1.jpg)

**Comment by tabacitu** [comment]
![Group 13](https://user-images.githubusercontent.com/1032474/96904896-b6705680-1465-11eb-9032-727dcd5a1ab4.jpg)

**Comment by tabacitu** [comment]
![Group 13](https://user-images.githubusercontent.com/1032474/96905266-3ac2d980-1466-11eb-81ec-27b83b8b6bbc.jpg)

**Comment by iordacheandrei** [comment]
![Group 13](https://user-images.githubusercontent.com/71145983/96907938-9c099d80-14a4-11eb-83a3-26e2260d908e.jpg)

**Comment by iordacheandrei** [comment]
![Group 14](https://user-images.githubusercontent.com/71145983/96907969-a7f55f80-14a4-11eb-984e-f2b54fff65ee.jpg)

**Comment by tabacitu** [comment]
![Group 14](https://user-images.githubusercontent.com/1032474/96909803-8aa49f00-146c-11eb-9252-bd894bf3d8bc.jpg)

**Comment by tabacitu** [comment]
![Group 16](https://user-images.githubusercontent.com/1032474/96910131-06065080-146d-11eb-9cfa-f5cb4d90aefd.jpg)

**Comment by tabacitu** [comment]
![96907938-9c099d80-14a4-11eb-83a3-26e2260d908e](https://user-images.githubusercontent.com/1032474/96910500-96dd2c00-146d-11eb-9e21-d33d2c95c814.jpg)
